## LATIHAN

## 1.Perkalian Matrix

In [8]:
import numpy as np
A = np.array([4, 9, 5])
B = np.array([7, 7, 4])

# Mengalikan matriks A dan B

kali = A * B
print(kali)


[28 63 20]


## 2.Pengurangan Matrix

In [9]:
import numpy as np

A = np.array([4, 9, 5])
B = np.array([7, 7, 4])

kurang = A - B
print(kurang)

[-3  2  1]


## 3.Transpose Matrix

In [11]:
import numpy as np

A = np.array([[4,9,5],[4,9,5]])

transpose_A = np.transpose(A)
print(transpose_A)

[[4 4]
 [9 9]
 [5 5]]


## 4.Nilai Invers

In [10]:
A = np.array([[4,9], [9,5]])

inverse_A = np.linalg.inv(A)
print("\ninvers matriks A:")
print(inverse_A)


invers matriks A:
[[-0.08196721  0.14754098]
 [ 0.14754098 -0.06557377]]


## 5.Nilai Determinan

In [12]:
import numpy as np

A = np.array([[4,9], [9,5]])

determinant_A = np.linalg.det(A)
print("Determinan dari matriks A:", determinant_A)

Determinan dari matriks A: -61.00000000000001
